minor changes

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -8,6 +8,10 @@ on:
   pull_request:
     branches: [ master ]
 #
+permissions:
+  pull-requests: write
+  issues: write
+  repository-projects: write
 jobs:
   build:
 
@@ -34,23 +38,23 @@ jobs:
           distribution: 'corretto'
       - name: "Set up environment"
         run: docker compose -f docker-compose.yml up -d --wait # wait until docker container started
-#      - name: "Wait for docker to finish building"
-#        run: sleep 10 # wait until docker container started
+      #      - name: "Wait for docker to finish building"
+      #        run: sleep 10 # wait until docker container started
       # The "Build with Maven" step runs the Maven `package` target in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
       - name: Build with Maven
         run: mvn clean install
       - name: Build with Maven
-        run: mvn clean install mvn test -Dspring.profiles.active=test
+        run: mvn test -Dspring.profiles.active=test
       # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
-#      - name: Update dependency graph
-#        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
-#      - name: Publish Test Report
-#        uses: mikepenz/action-junit-report@v1
-#        if: success() || failure() # always run even if the previous step fails
-#        with:
-#          report_paths: '**/build/test-results/test/TEST-*.xml'
-#      - name: Run JUnit Tests
-#        run: mvn test
+      #      - name: Update dependency graph
+      #        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+      #      - name: Publish Test Report
+      #        uses: mikepenz/action-junit-report@v1
+      #        if: success() || failure() # always run even if the previous step fails
+      #        with:
+      #          report_paths: '**/build/test-results/test/TEST-*.xml'
+      #      - name: Run JUnit Tests
+      #        run: mvn test
       - name: JUnit Test Report - converter-service
         uses: dorny/test-reporter@v1 #{owner}/{repository}@{ref}
         if: always()
